# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: aic.faq::lang.controllers.categories.reorder

# Attribute name
nameFrom: name

# Model Class name
modelClass: Aic\Faq\Models\Categories

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar