# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    created_at:
        label: aic.faq::lang.models.general.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    category:
        label: aic.faq::lang.models.category.label
        modelClass: Aic\Faq\Models\Categories
        conditions: category_id in (:filtered)
        options: getCategoriesListOptions
        nameFrom: name

    is_published:
        label: aic.faq::lang.models.general.published_status
        modelClass: Aic\Faq\Models\Faqs
        conditions: is_published in (:filtered)
        options: getPublishStatusOptions

    is_featured:
        label: aic.faq::lang.models.general.featured_status
        modelClass: Aic\Faq\Models\Faqs
        conditions: is_featured in (:filtered)
        options: getFeaturedStatusOptions
